type Superhero {
    id: ID!
    name: String
    powerstats: Powerstats!
    imageURL: String!
}

type Powerstats {
    intelligence: Int
    strength: Int
    durability: Int
    power: Int
    combat: Int
}

type Query {
    getAllSuperheroes: [Superhero]!
}

type Mutation {
    createSuperhero(input: CreateSuperheroInput): Superhero
    updateSuperheroStats(input: UpdateSuperheroStatsInput): Superhero
    deleteSuperhero: Superhero
}

input CreateSuperheroInput {
    name: String!
    powerstats: Powerstats!
    imageURL: String!
}

input UpdateSuperheroStatsInput {
    powerstats: Powerstats!
}